import type { Metadata } from "next";
import { Inter, Kanit } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer Section/Footer";
import FooterMenu from "./components/Footer Menu/FooterMenu";

const kanit = Kanit({ subsets: ["latin"], weight:["700","400"] });

export const metadata: Metadata = {
  title: "Twilight Assesment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kanit.className} h-screen lg:h-auto overflow-y-auto  m-0 p-0 relative`}
      >
        <Header />
        {children}
        <FooterMenu/>
        <Footer />
      </body>
    </html>
  );
}
